"""Add vote_count to Meme

Revision ID: 982add71c46a
Revises: e20d3b030575
Create Date: 2025-06-27 20:40:27.526448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982add71c46a'
down_revision = 'e20d3b030575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    # ### end Alembic commands ###
